site_name: AnyMotion API CLI

copyright: 'Copyright &copy; 2020 NTTPC Communications inc.'

theme:
  name: 'material'
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.ico'
  palette:
    primary: 'White'
    accent: 'Indigo'
  language: 'ja'
  extra:
    search:
      language: 'jp, en'
