[tool.poetry]
name = "encore-api-cli"
version = "0.9.0"
description = "Command Line Interface for AnyMotion API"
authors = ["Yusuke Kumihashi <y_kumiha@nttpc.co.jp>"]
readme = "README.md"
repository = "https://bitbucket.org/nttpc-datascience/encore-api-cli/"
classifiers = [
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8"
]

[tool.poetry.dependencies]
python = ">=3.6, <4"
click = "^7.1.1"
click_help_colors = "^0.6"
click_repl = "^0.1.6"
pygments = "^2.6.1"
requests = "^2.23.0"
tabulate = "^0.8.6"
yaspin = "^0.16.0"
encore-sdk = "^0.2.1"

[tool.poetry.dev-dependencies]
bandit = "^1.6.2"
black = "^19.10b0"
coverage = {version = "^5.0.3", extras = ["toml"]}
flake8 = "^3.7.9"
flake8-docstrings = "^1.5.0"
isort = "^4.3.21"
mypy = "^0.761"
pytest = "^5.3.5"
pytest-cov = "^2.8.1"
pytest-mock = "^2.0.0"
requests-mock = "^1.7.0"
tox = "^3.14.3"
s3pypi = "^0.10.1"

[tool.poetry.scripts]
amcli = "encore_api_cli.core:cli"
enimo = "encore_api_cli.core:cli"
encore = "encore_api_cli.core:cli"

[[tool.poetry.source]]
name = "anymotion"
# url = "https://pypi.anymotion.jp"
url = "http://pypi.anymotion.jp.s3-website-ap-northeast-1.amazonaws.com"

[tool.isort]
include_trailing_comma = true
line_length = 88
multi_line_output = 3

[tool.coverage.run]
source = ["encore_api_cli"]
branch = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
