version: 2.1
executors:
  default:
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
orbs:
  codecov: codecov/codecov@1.0.5
commands:
  restore_python:
    steps:
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Pipfile.lock" }}
            - v2-dependencies-

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_python
      - run:
          name: Install python packages
          command: |
            sudo pip install pipenv
            pipenv sync --dev
      - save_cache:
          paths:
            - .venv
          key: v2-dependencies-{{ checksum "Pipfile.lock" }}
  check-syntax:
    executor:
      name: default
    steps:
      - checkout
      - restore_python
      - run:
          name: Check syntax with flake8
          command: pipenv run flake8
  unit-test:
    executor:
      name: default
    steps:
      - checkout
      - restore_python
      - run:
          name: Run unit test with pytest
          command: pipenv run pytest -v --cov=encore_api_cli --cov-report=xml
      - codecov/upload:
          flags: unittest

workflows:
  build-and-test:
    jobs:
      - build
      - check-syntax:
          requires:
            - build
      - unit-test:
          requires:
            - build
