version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  aws-cli: circleci/aws-cli@0.1.19

commands:
  install_python:
    steps:
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install python packages
          command: poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

jobs:
  setup-py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - install_python
  test-py38: &test-template
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - install_python
      - run:
          name: Run unit test with pytest
          command: |
            mkdir test-reports
            poetry run pytest -v --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  test-py37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
  test-py36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
  measure-coverage:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - install_python
      - run:
          name: Run unit test with pytest
          command: poetry run pytest --cov=encore_api_cli --cov-report=xml
      - codecov/upload:
          flags: unittest
  check-syntax:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - install_python
      - run:
          name: Lint with flake8
          command: poetry run flake8
      - run:
          name: Lint with black
          command: poetry run black . --check
      - run:
          name: Lint with mypy
          command: poetry run mypy
  check-security:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - install_python
      - run:
          name: Check security with bandit
          command: poetry run bandit -r encore_api_cli -s B303
  build-and-upload:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Build
          command: poetry run build
      - run:
          name: Upload build file to S3
          command: |
            aws s3 sync dist s3://encore-api-cli
            aws s3 cp README.md s3://encore-api-cli
            aws s3 cp CHANGELOG.md s3://encore-api-cli
      - run:
          name: Notify slack
          command: |
            sed -e "s/<version>/${CIRCLE_TAG}/" .circleci/slack-message.json > message.json
            curl -X POST --data-urlencode payload@message.json ${SLACK_WEB_HOOK}

workflows:
  build-and-test:
    jobs:
      - setup-py38:
        filters:
          tags:
            only: /^\d.*/
      - test-py36:
          filters:
            tags:
              only: /^\d.*/
      - test-py37:
          filters:
            tags:
              only: /^\d.*/
      - test-py38:
          filters:
            tags:
              only: /^\d.*/
          requires:
            - setup-py38
      - measure-coverage:
          filters:
            tags:
              only: /^\d.*/
          requires:
            - setup-py38
      - check-syntax:
          filters:
            tags:
              only: /^\d.*/
          requires:
            - setup-py38
      - check-security:
          filters:
            tags:
              only: /^\d.*/
          requires:
            - setup-py38
      - build-and-upload:
          filters:
            tags:
              only: /^\d.*/
            branches:
              ignore: /.*/
          requires:
            - test-py36
            - test-py37
            - test-py38
            - measure-coverage
            - check-syntax
            - check-security
