version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test-py38: &test-template
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install python packages
          command: |
            sudo pip install pipenv
            pipenv sync
            rm Pipfile.lock
            pipenv install --dev
      - run:
          name: Run unit test with pytest
          command: |
            mkdir test-reports
            pipenv run pytest -v \
              --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  test-py37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
  test-py36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
  measure-coverage:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install python packages
          command: |
            sudo pip install pipenv
            pipenv sync --dev
      - run:
          name: Run unit test with pytest
          command: pipenv run pytest --cov=encore_api_cli --cov-report=xml
      - codecov/upload:
          flags: unittest
  check-syntax:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install python packages
          command: |
            sudo pip install pipenv
            pipenv sync --dev
      - run:
          name: Lint with flake8
          command: pipenv run flake8
      - run:
          name: Lint with black
          command: pipenv run black . --check
      - run:
          name: Lint with mypy
          command: pipenv run mypy
  check-security:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install python packages
          command: |
            sudo pip install pipenv
            pipenv sync --dev
      - run:
          name: Check security with bandit
          command: pipenv run bandit -r encore_api_cli -s B303

workflows:
  build-and-test:
    jobs:
      - test-py36
      - test-py37
      - test-py38
      - measure-coverage
      - check-syntax
      - check-security
